import 'dart:convert';

import 'package:flutter/services.dart' show AssetBundle, rootBundle;

import '../../models/geo.dart';
import '../../models/route_stop.dart';

/// Reads the generated map data in `assets/geo/` and `assets/landmarks.json`.
///
/// The three assets are produced offline by the scripts in `tool/`, never at
/// runtime, so parsing here is plain `jsonDecode` with no schema negotiation.
/// If a field is missing the value degrades to null rather than throwing: a
/// stop without a coordinate still has a name and a kilometre mark, and the
/// fare screen must keep working even when the map has nothing to draw.
class GeoAssets {
  GeoAssets({AssetBundle? bundle}) : _bundle = bundle ?? rootBundle;

  final AssetBundle _bundle;

  static const String routesAsset = 'assets/geo/routes.json';
  static const String stopsAsset = 'assets/geo/stops.json';
  static const String landmarksAsset = 'assets/landmarks.json';

  Future<Map<String, RouteGeometry>> loadGeometries() async {
    final decoded =
        jsonDecode(await _bundle.loadString(routesAsset)) as Map<String, dynamic>;
    final result = <String, RouteGeometry>{};
    for (final raw in decoded['routes'] as List<dynamic>? ?? const []) {
      final route = raw as Map<String, dynamic>;
      final geometry = RouteGeometry(
        codeName: route['codeName'] as String,
        siteName: route['siteName'] as String? ?? route['codeName'] as String,
        loop: (route['loop'] as List<dynamic>)
            .map((pair) => GeoPoint.fromLonLat((pair as List).cast<double>()))
            .toList(growable: false),
        turnaroundIndex: (route['turnaroundIndex'] as num?)?.toInt() ?? 0,
        onewayDm: ((route['onewayKm'] as num?)?.toDouble() ?? 0) * 10 ~/ 1,
        loopDm: ((route['loopKm'] as num?)?.toDouble() ?? 0) * 10 ~/ 1,
        declaredKm: (route['declaredKm'] as num?)?.toInt() ?? 0,
      );
      result[geometry.codeName] = geometry;
    }
    return result;
  }

  /// Per-route stop coordinates and measured distances, keyed by route.
  ///
  /// The returned map is sparse: a route only appears if it has geometry, and
  /// a stop only carries a position if `tool/place_stops.py` managed to snap
  /// it. Both absences are normal.
  Future<Map<String, Map<String, StopPlacement>>> loadStopPlacements() async {
    final decoded =
        jsonDecode(await _bundle.loadString(stopsAsset)) as Map<String, dynamic>;
    final result = <String, Map<String, StopPlacement>>{};
    for (final entry in (decoded['routes'] as Map<String, dynamic>? ?? {}).entries) {
      final rows = <String, StopPlacement>{};
      for (final raw in entry.value as List<dynamic>? ?? const []) {
        final stop = raw as Map<String, dynamic>;
        final name = stop['name'] as String;
        rows[name] = StopPlacement(
          lat: (stop['lat'] as num?)?.toDouble(),
          lng: (stop['lng'] as num?)?.toDouble(),
          // Null means "not fareable", and is distinct from 0.
          distDm: (stop['distDm'] as num?)?.toInt(),
          source: stop['source'] as String? ?? 'unknown',
        );
      }
      result[entry.key] = rows;
    }
    return result;
  }

  Future<List<MapLandmark>> loadLandmarks() async {
    final decoded =
        jsonDecode(await _bundle.loadString(landmarksAsset)) as Map<String, dynamic>;
    return (decoded['landmarks'] as List<dynamic>? ?? const [])
        .map((raw) => raw as Map<String, dynamic>)
        .map(
          (entry) => MapLandmark(
            name: entry['name'] as String,
            category: entry['category'] as String? ?? 'landmark',
            lat: (entry['lat'] as num).toDouble(),
            lng: (entry['lng'] as num).toDouble(),
            source: entry['source'] as String? ?? 'unknown',
            routeCodes: (entry['routes'] as List<dynamic>? ?? const [])
                .cast<String>(),
          ),
        )
        .toList(growable: false);
  }

  /// A fingerprint of the bundled map data.
  ///
  /// Cheap: asset lengths and the route count are enough to notice that the
  /// generated data changed underneath an existing install. A full hash would
  /// be more precise but this runs on every cold start, and a false "changed"
  /// only costs one re-seed.
  Future<String> contentFingerprint() async {
    final routes = await _bundle.load(routesAsset);
    final stops = await _bundle.load(stopsAsset);
    final landmarks = await _bundle.load(landmarksAsset);
    return '${routes.lengthInBytes}-${stops.lengthInBytes}-${landmarks.lengthInBytes}';
  }
}

/// Where a stop sits, as generated by `tool/place_stops.py`.
class StopPlacement {
  const StopPlacement({
    required this.lat,
    required this.lng,
    required this.distDm,
    required this.source,
  });

  final double? lat;
  final double? lng;
  final int? distDm;

  /// `geocoded` when the stop was snapped onto the polyline, `interpolated`
  /// when its position was guessed from its kilometre mark for display only.
  final String source;

  /// True when this position is a real measurement worth trusting.
  bool get isMeasured => distDm != null && source == 'geocoded';

  /// Applies a placement to a parsed stop, leaving it untouched when the
  /// placement is missing.
  RouteStop applyTo(RouteStop stop) {
    if (distDm == null && lat == null) return stop;
    return stop.copyWith(lat: lat, lng: lng, distDm: distDm);
  }
}
